export const ARCHIVED_FORMULA_CONSTANTS = {
  COLLECTION_NAME: 'archivedFormulas',
} as const;

export const ARCHIVED_FORMULA_REASON = {
  EGGS_DESTROYED: 'EGGS_DESTROYED',
  ARCHIVED_BY_USER: 'ARCHIVED_BY_USER',
  ALL_CHICKS_REGISTERED: 'ALL_CHICKS_REGISTERED',
} as const;
