import { CountryCode } from '../enums';
import { ICountries } from '../interfaces';

export const COUNTRIES = [
  { name: 'Afghanistan', alp3: 'AFG', currencyCode: '004', prefix: '+93' },
  { name: 'Aland Islands', alp3: 'ALA', currencyCode: '248', prefix: '+358' },
  { name: 'Albania', alp3: 'ALB', currencyCode: '008', prefix: '+355' },
  { name: 'Algeria', alp3: 'DZA', currencyCode: '012', prefix: '+213' },
  { name: 'American Samoa', alp3: 'ASM', currencyCode: '016', prefix: '+1-684' },
  { name: 'Andorra', alp3: 'AND', currencyCode: '020', prefix: '+376' },
  { name: 'Angola', alp3: 'AGO', currencyCode: '024', prefix: '+244' },
  { name: 'Anguilla', alp3: 'AIA', currencyCode: '660', prefix: '+1-264' },
  { name: 'Antarctica', alp3: 'ATA', currencyCode: '010', prefix: '+672' },
  { name: 'Antigua and Barbuda', alp3: 'ATG', currencyCode: '028', prefix: '+1-268' },
  { name: 'Argentina', alp3: 'ARG', currencyCode: '032', prefix: '+54' },
  { name: 'Armenia', alp3: 'ARM', currencyCode: '051', prefix: '+374' },
  { name: 'Aruba', alp3: 'ABW', currencyCode: '533', prefix: '+297' },
  { name: 'Australia', alp3: 'AUS', currencyCode: '036', prefix: '+61' },
  { name: 'Austria', alp3: 'AUT', currencyCode: '040', prefix: '+43' },
  { name: 'Azerbaijan', alp3: 'AZE', currencyCode: '031', prefix: '+994' },
  { name: 'Bahamas', alp3: 'BHS', currencyCode: '044', prefix: '+1-242' },
  { name: 'Bahrain', alp3: 'BHR', currencyCode: '048', prefix: '+973' },
  { name: 'Bangladesh', alp3: 'BGD', currencyCode: '050', prefix: '+880' },
  { name: 'Barbados', alp3: 'BRB', currencyCode: '052', prefix: '+1-246' },
  { name: 'Belarus', alp3: 'BLR', currencyCode: '112', prefix: '+375' },
  { name: 'Belgium', alp3: 'BEL', currencyCode: '056', prefix: '+32' },
  { name: 'Belize', alp3: 'BLZ', currencyCode: '084', prefix: '+501' },
  { name: 'Benin', alp3: 'BEN', currencyCode: '204', prefix: '+229' },
  { name: 'Bermuda', alp3: 'BMU', currencyCode: '060', prefix: '+1-441' },
  { name: 'Bhutan', alp3: 'BTN', currencyCode: '064', prefix: '+975' },
  { name: 'Bolivia, Plurinational State of', alp3: 'BOL', currencyCode: '068', prefix: '+591' },
  { name: 'Bonaire, Sint Eustatius and Saba', alp3: 'BES', currencyCode: '535', prefix: '+599' },
  { name: 'Bosnia and Herzegovina', alp3: 'BIH', currencyCode: '070', prefix: '+387' },
  { name: 'Botswana', alp3: 'BWA', currencyCode: '072', prefix: '+267' },
  { name: 'Bouvet Island', alp3: 'BVT', currencyCode: '074', prefix: '+47' },
  { name: 'Brazil', alp3: 'BRA', currencyCode: '076', prefix: '+55' },
  { name: 'British Indian Ocean Territory', alp3: 'IOT', currencyCode: '086', prefix: '+246' },
  { name: 'Brunei Darussalam', alp3: 'BRN', currencyCode: '096', prefix: '+673' },
  { name: 'Bulgaria', alp3: 'BGR', currencyCode: '100', prefix: '+359' },
  { name: 'Burkina Faso', alp3: 'BFA', currencyCode: '854', prefix: '+226' },
  { name: 'Burundi', alp3: 'BDI', currencyCode: '108', prefix: '+257' },
  { name: 'Cabo Verde', alp3: 'CPV', currencyCode: '132', prefix: '+238' },
  { name: 'Cambodia', alp3: 'KHM', currencyCode: '116', prefix: '+855' },
  { name: 'Cameroon', alp3: 'CMR', currencyCode: '120', prefix: '+237' },
  { name: 'Canada', alp3: 'CAN', currencyCode: '124', prefix: '+1' },
  { name: 'Cayman Islands', alp3: 'CYM', currencyCode: '136', prefix: '+1-345' },
  { name: 'Central African Republic', alp3: 'CAF', currencyCode: '140', prefix: '+236' },
  { name: 'Chad', alp3: 'TCD', currencyCode: '148', prefix: '+235' },
  { name: 'Chile', alp3: 'CHL', currencyCode: '152', prefix: '+56' },
  { name: 'China', alp3: 'CHN', currencyCode: '156', prefix: '+86' },
  { name: 'Christmas Island', alp3: 'CXR', currencyCode: '162', prefix: '+61' },
  { name: 'Cocos (Keeling) Islands', alp3: 'CCK', currencyCode: '166', prefix: '+61' },
  { name: 'Colombia', alp3: 'COL', currencyCode: '170', prefix: '+57' },
  { name: 'Comoros', alp3: 'COM', currencyCode: '174', prefix: '+269' },
  { name: 'Congo', alp3: 'COG', currencyCode: '178', prefix: '+242' },
  { name: 'Congo, Democratic Republic of the', alp3: 'COD', currencyCode: '180', prefix: '+243' },
  { name: 'Cook Islands', alp3: 'COK', currencyCode: '184', prefix: '+682' },
  { name: 'Costa Rica', alp3: 'CRI', currencyCode: '188', prefix: '+506' },
  { name: "Côte d'Ivoire", alp3: 'CIV', currencyCode: '384', prefix: '+225' },
  { name: 'Croatia', alp3: 'HRV', currencyCode: '191', prefix: '+385' },
  { name: 'Cuba', alp3: 'CUB', currencyCode: '192', prefix: '+53' },
  { name: 'Curaçao', alp3: 'CUW', currencyCode: '531', prefix: '+599' },
  { name: 'Cyprus', alp3: 'CYP', currencyCode: '196', prefix: '+357' },
  { name: 'Czechia', alp3: 'CZE', currencyCode: '203', prefix: '+420' },
  { name: 'Denmark', alp3: 'DNK', currencyCode: '208', prefix: '+45' },
  { name: 'Djibouti', alp3: 'DJI', currencyCode: '262', prefix: '+253' },
  { name: 'Dominica', alp3: 'DMA', currencyCode: '212', prefix: '+1-767' },
  { name: 'Dominican Republic', alp3: 'DOM', currencyCode: '214', prefix: '+1-809' },
  { name: 'Ecuador', alp3: 'ECU', currencyCode: '218', prefix: '+593' },
  { name: 'Egypt', alp3: 'EGY', currencyCode: '818', prefix: '+20' },
  { name: 'El Salvador', alp3: 'SLV', currencyCode: '222', prefix: '+503' },
  { name: 'Equatorial Guinea', alp3: 'GNQ', currencyCode: '226', prefix: '+240' },
  { name: 'Eritrea', alp3: 'ERI', currencyCode: '232', prefix: '+291' },
  { name: 'Estonia', alp3: 'EST', currencyCode: '233', prefix: '+372' },
  { name: 'Eswatini', alp3: 'SWZ', currencyCode: '748', prefix: '+268' },
  { name: 'Ethiopia', alp3: 'ETH', currencyCode: '231', prefix: '+251' },
  { name: 'Falkland Islands (Malvinas)', alp3: 'FLK', currencyCode: '238', prefix: '+500' },
  { name: 'Faroe Islands', alp3: 'FRO', currencyCode: '234', prefix: '+298' },
  { name: 'Fiji', alp3: 'FJI', currencyCode: '242', prefix: '+679' },
  { name: 'Finland', alp3: 'FIN', currencyCode: '246', prefix: '+358' },
  { name: 'France', alp3: 'FRA', currencyCode: '250', prefix: '+33' },
  { name: 'French Guiana', alp3: 'GUF', currencyCode: '254', prefix: '+594' },
  { name: 'French Polynesia', alp3: 'PYF', currencyCode: '258', prefix: '+689' },
  { name: 'French Southern Territories', alp3: 'ATF', currencyCode: '260', prefix: '+262' },
  { name: 'Gabon', alp3: 'GAB', currencyCode: '266', prefix: '+241' },
  { name: 'Gambia', alp3: 'GMB', currencyCode: '270', prefix: '+220' },
  { name: 'Georgia', alp3: 'GEO', currencyCode: '268', prefix: '+995' },
  { name: 'Germany', alp3: 'DEU', currencyCode: '276', prefix: '+49' },
  { name: 'Ghana', alp3: 'GHA', currencyCode: '288', prefix: '+233' },
  { name: 'Gibraltar', alp3: 'GIB', currencyCode: '292', prefix: '+350' },
  { name: 'Greece', alp3: 'GRC', currencyCode: '300', prefix: '+30' },
  { name: 'Greenland', alp3: 'GRL', currencyCode: '304', prefix: '+299' },
  { name: 'Grenada', alp3: 'GRD', currencyCode: '308', prefix: '+1-473' },
  { name: 'Guadeloupe', alp3: 'GLP', currencyCode: '312', prefix: '+590' },
  { name: 'Guam', alp3: 'GUM', currencyCode: '316', prefix: '+1-671' },
  { name: 'Guatemala', alp3: 'GTM', currencyCode: '320', prefix: '+502' },
  { name: 'Guernsey', alp3: 'GGY', currencyCode: '831', prefix: '+44' },
  { name: 'Guinea', alp3: 'GIN', currencyCode: '324', prefix: '+224' },
  { name: 'Guinea-Bissau', alp3: 'GNB', currencyCode: '624', prefix: '+245' },
  { name: 'Guyana', alp3: 'GUY', currencyCode: '328', prefix: '+592' },
  { name: 'Haiti', alp3: 'HTI', currencyCode: '332', prefix: '+509' },
  { name: 'Heard Island and McDonald Islands', alp3: 'HMD', currencyCode: '334', prefix: '+672' },
  { name: 'Holy See', alp3: 'VAT', currencyCode: '336', prefix: '+379' },
  { name: 'Honduras', alp3: 'HND', currencyCode: '340', prefix: '+504' },
  { name: 'Hong Kong', alp3: 'HKG', currencyCode: '344', prefix: '+852' },
  { name: 'Hungary', alp3: 'HUN', currencyCode: '348', prefix: '+36' },
  { name: 'Iceland', alp3: 'ISL', currencyCode: '352', prefix: '+354' },
  { name: 'India', alp3: 'IND', currencyCode: '356', prefix: '+91' },
  { name: 'Indonesia', alp3: 'IDN', currencyCode: '360', prefix: '+62' },
  { name: 'Iran, Islamic Republic of', alp3: 'IRN', currencyCode: '364', prefix: '+98' },
  { name: 'Iraq', alp3: 'IRQ', currencyCode: '368', prefix: '+964' },
  { name: 'Ireland', alp3: 'IRL', currencyCode: '372', prefix: '+353' },
  { name: 'Isle of Man', alp3: 'IMN', currencyCode: '833', prefix: '+44' },
  { name: 'Israel', alp3: 'ISR', currencyCode: '376', prefix: '+972' },
  { name: 'Italy', alp3: 'ITA', currencyCode: '380', prefix: '+39' },
  { name: 'Jamaica', alp3: 'JAM', currencyCode: '388', prefix: '+1-876' },
  { name: 'Japan', alp3: 'JPN', currencyCode: '392', prefix: '+81' },
  { name: 'Jersey', alp3: 'JEY', currencyCode: '832', prefix: '+44' },
  { name: 'Jordan', alp3: 'JOR', currencyCode: '400', prefix: '+962' },
  { name: 'Kazakhstan', alp3: 'KAZ', currencyCode: '398', prefix: '+7' },
  { name: 'Kenya', alp3: 'KEN', currencyCode: '404', prefix: '+254' },
  { name: 'Kiribati', alp3: 'KIR', currencyCode: '296', prefix: '+686' },
  { name: "Korea, Democratic People's Republic of", alp3: 'PRK', currencyCode: '408', prefix: '+850' },
  { name: 'Korea, Republic of', alp3: 'KOR', currencyCode: '410', prefix: '+82' },
  { name: 'Kuwait', alp3: 'KWT', currencyCode: '414', prefix: '+965' },
  { name: 'Kyrgyzstan', alp3: 'KGZ', currencyCode: '417', prefix: '+996' },
  { name: "Lao People's Democratic Republic", alp3: 'LAO', currencyCode: '418', prefix: '+856' },
  { name: 'Latvia', alp3: 'LVA', currencyCode: '428', prefix: '+371' },
  { name: 'Lebanon', alp3: 'LBN', currencyCode: '422', prefix: '+961' },
  { name: 'Lesotho', alp3: 'LSO', currencyCode: '426', prefix: '+266' },
  { name: 'Liberia', alp3: 'LBR', currencyCode: '430', prefix: '+231' },
  { name: 'Libya', alp3: 'LBY', currencyCode: '434', prefix: '+218' },
  { name: 'Liechtenstein', alp3: 'LIE', currencyCode: '438', prefix: '+423' },
  { name: 'Lithuania', alp3: 'LTU', currencyCode: '440', prefix: '+370' },
  { name: 'Luxembourg', alp3: 'LUX', currencyCode: '442', prefix: '+352' },
  { name: 'Macao', alp3: 'MAC', currencyCode: '446', prefix: '+853' },
  { name: 'Madagascar', alp3: 'MDG', currencyCode: '450', prefix: '+261' },
  { name: 'Malawi', alp3: 'MWI', currencyCode: '454', prefix: '+265' },
  { name: 'Malaysia', alp3: 'MYS', currencyCode: '458', prefix: '+60' },
  { name: 'Maldives', alp3: 'MDV', currencyCode: '462', prefix: '+960' },
  { name: 'Mali', alp3: 'MLI', currencyCode: '466', prefix: '+223' },
  { name: 'Malta', alp3: 'MLT', currencyCode: '470', prefix: '+356' },
  { name: 'Marshall Islands', alp3: 'MHL', currencyCode: '584', prefix: '+692' },
  { name: 'Martinique', alp3: 'MTQ', currencyCode: '474', prefix: '+596' },
  { name: 'Mauritania', alp3: 'MRT', currencyCode: '478', prefix: '+222' },
  { name: 'Mauritius', alp3: 'MUS', currencyCode: '480', prefix: '+230' },
  { name: 'Mayotte', alp3: 'MYT', currencyCode: '175', prefix: '+262' },
  { name: 'Mexico', alp3: 'MEX', currencyCode: '484', prefix: '+52' },
  { name: 'Micronesia, Federated States of', alp3: 'FSM', currencyCode: '583', prefix: '+691' },
  { name: 'Moldova, Republic of', alp3: 'MDA', currencyCode: '498', prefix: '+373' },
  { name: 'Monaco', alp3: 'MCO', currencyCode: '492', prefix: '+377' },
  { name: 'Mongolia', alp3: 'MNG', currencyCode: '496', prefix: '+976' },
  { name: 'Montenegro', alp3: 'MNE', currencyCode: '499', prefix: '+382' },
  { name: 'Montserrat', alp3: 'MSR', currencyCode: '500', prefix: '+1-664' },
  { name: 'Morocco', alp3: 'MAR', currencyCode: '504', prefix: '+212' },
  { name: 'Mozambique', alp3: 'MOZ', currencyCode: '508', prefix: '+258' },
  { name: 'Myanmar', alp3: 'MMR', currencyCode: '104', prefix: '+95' },
  { name: 'Namibia', alp3: 'NAM', currencyCode: '516', prefix: '+264' },
  { name: 'Nauru', alp3: 'NRU', currencyCode: '520', prefix: '+674' },
  { name: 'Nepal', alp3: 'NPL', currencyCode: '524', prefix: '+977' },
  { name: 'Netherlands, Kingdom of the', alp3: 'NLD', currencyCode: '528', prefix: '+31' },
  { name: 'New Caledonia', alp3: 'NCL', currencyCode: '540', prefix: '+687' },
  { name: 'New Zealand', alp3: 'NZL', currencyCode: '554', prefix: '+64' },
  { name: 'Nicaragua', alp3: 'NIC', currencyCode: '558', prefix: '+505' },
  { name: 'Niger', alp3: 'NER', currencyCode: '562', prefix: '+227' },
  { name: 'Nigeria', alp3: 'NGA', currencyCode: '566', prefix: '+234' },
  { name: 'Niue', alp3: 'NIU', currencyCode: '570', prefix: '+683' },
  { name: 'Norfolk Island', alp3: 'NFK', currencyCode: '574', prefix: '+672' },
  { name: 'North Macedonia', alp3: 'MKD', currencyCode: '807', prefix: '+389' },
  { name: 'Northern Mariana Islands', alp3: 'MNP', currencyCode: '580', prefix: '+1-670' },
  { name: 'Norway', alp3: 'NOR', currencyCode: '578', prefix: '+47' },
  { name: 'Oman', alp3: 'OMN', currencyCode: '512', prefix: '+968' },
  { name: 'Pakistan', alp3: 'PAK', currencyCode: '586', prefix: '+92' },
  { name: 'Palau', alp3: 'PLW', currencyCode: '585', prefix: '+680' },
  { name: 'Palestine, State of', alp3: 'PSE', currencyCode: '275', prefix: '+970' },
  { name: 'Panama', alp3: 'PAN', currencyCode: '591', prefix: '+507' },
  { name: 'Papua New Guinea', alp3: 'PNG', currencyCode: '598', prefix: '+675' },
  { name: 'Paraguay', alp3: 'PRY', currencyCode: '600', prefix: '+595' },
  { name: 'Peru', alp3: 'PER', currencyCode: '604', prefix: '+51' },
  { name: 'Philippines', alp3: 'PHL', currencyCode: '608', prefix: '+63' },
  { name: 'Pitcairn', alp3: 'PCN', currencyCode: '612', prefix: '+64' },
  { name: 'Poland', alp3: 'POL', currencyCode: '616', prefix: '+48' },
  { name: 'Portugal', alp3: 'PRT', currencyCode: '620', prefix: '+351' },
  { name: 'Puerto Rico', alp3: 'PRI', currencyCode: '630', prefix: '+1-787' },
  { name: 'Qatar', alp3: 'QAT', currencyCode: '634', prefix: '+974' },
  { name: 'Réunion', alp3: 'REU', currencyCode: '638', prefix: '+262' },
  { name: 'Romania', alp3: 'ROU', currencyCode: '642', prefix: '+40' },
  { name: 'Russian Federation', alp3: 'RUS', currencyCode: '643', prefix: '+7' },
  { name: 'Rwanda', alp3: 'RWA', currencyCode: '646', prefix: '+250' },
  { name: 'Saint Barthélemy', alp3: 'BLM', currencyCode: '652', prefix: '+590' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', alp3: 'SHN', currencyCode: '654', prefix: '+290' },
  { name: 'New Zealand', alp3: 'NZL', currencyCode: '554', prefix: '+64' },
  { name: 'Nicaragua', alp3: 'NIC', currencyCode: '558', prefix: '+505' },
  { name: 'Niger', alp3: 'NER', currencyCode: '562', prefix: '+227' },
  { name: 'Nigeria', alp3: 'NGA', currencyCode: '566', prefix: '+234' },
  { name: 'Niue', alp3: 'NIU', currencyCode: '570', prefix: '+683' },
  { name: 'Norfolk Island', alp3: 'NFK', currencyCode: '574', prefix: '+672' },
  { name: 'North Macedonia', alp3: 'MKD', currencyCode: '807', prefix: '+389' },
  { name: 'Northern Mariana Islands', alp3: 'MNP', currencyCode: '580', prefix: '+1670' },
  { name: 'Norway', alp3: 'NOR', currencyCode: '578', prefix: '+47' },
  { name: 'Oman', alp3: 'OMN', currencyCode: '512', prefix: '+968' },
  { name: 'Pakistan', alp3: 'PAK', currencyCode: '586', prefix: '+92' },
  { name: 'Palau', alp3: 'PLW', currencyCode: '585', prefix: '+680' },
  { name: 'Palestine, State of', alp3: 'PSE', currencyCode: '275', prefix: '+970' },
  { name: 'Panama', alp3: 'PAN', currencyCode: '591', prefix: '+507' },
  { name: 'Papua New Guinea', alp3: 'PNG', currencyCode: '598', prefix: '+675' },
  { name: 'Paraguay', alp3: 'PRY', currencyCode: '600', prefix: '+595' },
  { name: 'Peru', alp3: 'PER', currencyCode: '604', prefix: '+51' },
  { name: 'Philippines', alp3: 'PHL', currencyCode: '608', prefix: '+63' },
  { name: 'Pitcairn', alp3: 'PCN', currencyCode: '612', prefix: '+872' },
  { name: 'Poland', alp3: 'POL', currencyCode: '616', prefix: '+48' },
  { name: 'Portugal', alp3: 'PRT', currencyCode: '620', prefix: '+351' },
  { name: 'Puerto Rico', alp3: 'PRI', currencyCode: '630', prefix: '+1' },
  { name: 'Qatar', alp3: 'QAT', currencyCode: '634', prefix: '+974' },
  { name: 'Réunion', alp3: 'REU', currencyCode: '638', prefix: '+262' },
  { name: 'Romania', alp3: 'ROU', currencyCode: '642', prefix: '+40' },
  { name: 'Russian Federation', alp3: 'RUS', currencyCode: '643', prefix: '+7' },
  { name: 'Rwanda', alp3: 'RWA', currencyCode: '646', prefix: '+250' },
  { name: 'Saint Barthélemy', alp3: 'BLM', currencyCode: '652', prefix: '+590' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', alp3: 'SHN', currencyCode: '654', prefix: '+290' },
  { name: 'Saint Kitts and Nevis', alp3: 'KNA', currencyCode: '659', prefix: '+1-869' },
  { name: 'Saint Lucia', alp3: 'LCA', currencyCode: '662', prefix: '+1-758' },
  { name: 'Saint Martin (French part)', alp3: 'MAF', currencyCode: '663', prefix: '+590' },
  { name: 'Saint Pierre and Miquelon', alp3: 'SPM', currencyCode: '666', prefix: '+508' },
  { name: 'Saint Vincent and the Grenadines', alp3: 'VCT', currencyCode: '670', prefix: '+1-784' },
  { name: 'Samoa', alp3: 'WSM', currencyCode: '882', prefix: '+685' },
  { name: 'San Marino', alp3: 'SMR', currencyCode: '674', prefix: '+378' },
  { name: 'Sao Tome and Principe', alp3: 'STP', currencyCode: '678', prefix: '+239' },
  { name: 'Saudi Arabia', alp3: 'SAU', currencyCode: '682', prefix: '+966' },
  { name: 'Senegal', alp3: 'SEN', currencyCode: '686', prefix: '+221' },
  { name: 'Serbia', alp3: 'SRB', currencyCode: '688', prefix: '+381' },
  { name: 'Seychelles', alp3: 'SYC', currencyCode: '690', prefix: '+248' },
  { name: 'Sierra Leone', alp3: 'SLE', currencyCode: '694', prefix: '+232' },
  { name: 'Singapore', alp3: 'SGP', currencyCode: '702', prefix: '+65' },
  { name: 'Sint Maarten (Dutch part)', alp3: 'SXM', currencyCode: '534', prefix: '+1-721' },
  { name: 'Slovakia', alp3: 'SVK', currencyCode: '703', prefix: '+421' },
  { name: 'Slovenia', alp3: 'SVN', currencyCode: '705', prefix: '+386' },
  { name: 'Solomon Islands', alp3: 'SLB', currencyCode: '090', prefix: '+677' },
  { name: 'Somalia', alp3: 'SOM', currencyCode: '706', prefix: '+252' },
  { name: 'South Africa', alp3: 'ZAF', currencyCode: '710', prefix: '+27' },
  { name: 'South Georgia and the South Sandwich Islands', alp3: 'SGS', currencyCode: '239', prefix: '+500' },
  { name: 'South Sudan', alp3: 'SSD', currencyCode: '728', prefix: '+211' },
  { name: 'Spain', alp3: 'ESP', currencyCode: '724', prefix: '+34' },
  { name: 'Sri Lanka', alp3: 'LKA', currencyCode: '144', prefix: '+94' },
  { name: 'Sudan', alp3: 'SDN', currencyCode: '729', prefix: '+249' },
  { name: 'Suriname', alp3: 'SUR', currencyCode: '740', prefix: '+597' },
  { name: 'Svalbard and Jan Mayen', alp3: 'SJM', currencyCode: '744', prefix: '+47' },
  { name: 'Sweden', alp3: 'SWE', currencyCode: '752', prefix: '+46' },
  { name: 'Switzerland', alp3: 'CHE', currencyCode: '756', prefix: '+41' },
  { name: 'Syrian Arab Republic', alp3: 'SYR', currencyCode: '760', prefix: '+963' },
  { name: 'Taiwan, Province of China', alp3: 'TWN', currencyCode: '158', prefix: '+886' },
  { name: 'Tajikistan', alp3: 'TJK', currencyCode: '762', prefix: '+992' },
  { name: 'Tanzania, United Republic of', alp3: 'TZA', currencyCode: '834', prefix: '+255' },
  { name: 'Thailand', alp3: 'THA', currencyCode: '764', prefix: '+66' },
  { name: 'Timor-Leste', alp3: 'TLS', currencyCode: '626', prefix: '+670' },
  { name: 'Togo', alp3: 'TGO', currencyCode: '768', prefix: '+228' },
  { name: 'Tokelau', alp3: 'TKL', currencyCode: '772', prefix: '+690' },
  { name: 'Tonga', alp3: 'TON', currencyCode: '776', prefix: '+676' },
  { name: 'Trinidad and Tobago', alp3: 'TTO', currencyCode: '780', prefix: '+1-868' },
  { name: 'Tunisia', alp3: 'TUN', currencyCode: '788', prefix: '+216' },
  { name: 'Turkey', alp3: 'TUR', currencyCode: '792', prefix: '+90' },
  { name: 'Turkmenistan', alp3: 'TKM', currencyCode: '795', prefix: '+993' },
  { name: 'Turks and Caicos Islands', alp3: 'TCA', currencyCode: '796', prefix: '+1-649' },
  { name: 'Tuvalu', alp3: 'TUV', currencyCode: '798', prefix: '+688' },
  { name: 'Uganda', alp3: 'UGA', currencyCode: '800', prefix: '+256' },
  { name: 'Ukraine', alp3: 'UKR', currencyCode: '804', prefix: '+380' },
  { name: 'United Arab Emirates', alp3: 'ARE', currencyCode: '784', prefix: '+971' },
  { name: 'United Kingdom', alp3: 'GBR', currencyCode: '826', prefix: '+44' },
  { name: 'United States of America', alp3: 'USA', currencyCode: '840', prefix: '+1' },
  { name: 'Uruguay', alp3: 'URY', currencyCode: '858', prefix: '+598' },
  { name: 'Uzbekistan', alp3: 'UZB', currencyCode: '860', prefix: '+998' },
  { name: 'Vanuatu', alp3: 'VUT', currencyCode: '548', prefix: '+678' },
  { name: 'Venezuela (Bolivarian Republic of)', alp3: 'VEN', currencyCode: '862', prefix: '+58' },
  { name: 'Viet Nam', alp3: 'VNM', currencyCode: '704', prefix: '+84' },
  { name: 'Wallis and Futuna', alp3: 'WLF', currencyCode: '876', prefix: '+681' },
  { name: 'Western Sahara', alp3: 'ESH', currencyCode: '732', prefix: '+212' },
  { name: 'Yemen', alp3: 'YEM', currencyCode: '887', prefix: '+967' },
  { name: 'Zambia', alp3: 'ZMB', currencyCode: '894', prefix: '+260' },
  { name: 'Zimbabwe', alp3: 'ZWE', currencyCode: '716', prefix: '+263' },
] as const;

export const COUNTRY_DETAILS_BY_ALP3: Record<CountryCode, ICountries> = COUNTRIES.reduce(
  (acc, country) => {
    acc[country.alp3] = country;
    return acc;
  },
  {} as Record<CountryCode, ICountries>,
);
