export const PIGEON_CONSTANTS = {
  COLLECTION_NAME: 'pigeons',
  MAX_NAME_LENGTH: 100,
  MAX_FATHER_NAME_LENGTH: 100,
  MAX_MOTHER_NAME_LENGTH: 100,
  MAX_RING_NO_LENGTH: 20,
  MAX_RING_COLOR_LENGTH: 30,
  MAX_CASE_NUMBER_LENGTH: 50,
  MAX_OWNER_ID_LENGTH: 100,
  YEAR_OF_BIRTH_PATTERN: /^\d{4}$/,
  DOCUMENTATION_NO_PATTERN: /^\d{4}-[A-Z]-\d{3}$/,
  RING_NO_PATTERN: /^[A-Z0-9]+$/,
} as const;

export const PIGEON_MESSAGES = {
  CREATED: 'Pigeon created successfully',
  UPDATED: 'Pigeon updated successfully',
  DELETED: 'Pigeon deleted successfully',
  NOT_FOUND: 'Pigeon not found',
  ALREADY_EXISTS: 'Pigeon already exists',
  INVALID_PARENT: 'Invalid parent pigeon',
  INVALID_STATUS_TRANSITION: 'Invalid status transition',
  INVALID_DOCUMENTATION_NUMBER: 'Invalid documentation number format',
  INVALID_YEAR_OF_BIRTH: 'Invalid year of birth format',
  PARENT_NOT_ALIVE: 'Parent pigeon is not alive',
  PARENT_WRONG_GENDER: 'Parent pigeon has wrong gender',
  DEAD_PIGEON_CANNOT_CHANGE_STATUS: 'Dead pigeon cannot change status',
  SOLD_PIGEON_CANNOT_BE_ALIVE: 'Sold pigeon cannot be changed to alive',
  DEAD_AT_REQUIRED: 'Dead date is required when changing status to DEAD',
} as const;

export const REGISTRATION_NUMBER_CONSTANTS = {
  PATTERN: /^\d{4}-[A-Z]-\d{3}$/,
  LETTERS: [
    'A',
    'B',
    'C',
    'D',
    'E',
    'F',
    'G',
    'H',
    'I',
    'J',
    'K',
    'L',
    'M',
    'N',
    'O',
    'P',
    'Q',
    'R',
    'S',
    'T',
    'U',
    'V',
    'W',
    'X',
    'Y',
    'Z',
  ],
  MAX_SEQUENCE: 999,
  SEQUENCE_PADDING: 3,
} as const;
